### ISSUE TITLE
トップページのテストのエラーについて

### ISSUE THREAD

**Issue by shizuka12** [shizuka12/final-tasks#4]
トップページにすべての投稿が表示されるようにしたため、そのテストコードを書いたのですが、この37行目で、`TypeError: 'NoneType' object is not subscriptable`というエラーが出てしまいました。

https://docs.djangoproject.com/ja/3.2/intro/tutorial05/#:~:text=def%20test_past_question,[question]&#44;)
以前取り組んだこちらの「新しいビューをテストする」のところとやっていることが似ていたので、同じようなコードを書いていたのですが、なぜこの時はエラーにならなかったのに、今回はエラーになってしまったのかがよく分かりません。
https://github.com/shizuka12/final-tasks/blob/0f113c3c397a8cbaf49b74daa3fd7b2385c30aa6/mysite/tmitter/tests.py#L9-L39

**Comment by shunsuke44** [comment]
`response`をprintデバッグしてみると、リダイレクトが返ってきていました。
`test_of_timeline`の最初でログインしているユーザはデータベース上に作成されていなくないですか？

**Comment by shizuka12** [comment]
`test_of_timeline`の最初でログインしているユーザがデータベース上に作成されていなかったことにより、ログインができずリダイレクトが返ってきて、その結果として37行目がエラーになってしまっていたようでした。
きちんとユーザーを作成したところ、テストに成功しました。
ありがとうございました。
