### ISSUE TITLE
アカウントページのquerysetの並び順について

### ISSUE THREAD

**Issue by shizuka12** [shizuka12/final-tasks#5]
アカウントページに、投稿が新しい順に表示されるかどうかのテストを作成していたのですが、59行目のquerysetを60行目でデバッグしたところ、`<QuerySet [<Tmeet: This is a accountpage test1 by username2>, <Tmeet: This is a accountpage test2 by username2>]>`と出力され、古い順に並んでしまっていました。
https://github.com/shizuka12/final-tasks/blob/509ad43d033ecff4d0e87c425a3b3161df5a69be/mysite/tmitter/tests.py#L35-L62
<br>
ちなみにこのtmeet_listはビューでこのように定義していて、
https://github.com/shizuka12/final-tasks/blob/509ad43d033ecff4d0e87c425a3b3161df5a69be/mysite/tmitter/views.py#L23
実際にサーバーを起動してアカウントページを見た時にはきちんと新しい順に並んで表示されていました。

なぜ、このquerysetは古い順に並んでしまっているのでしょうか？

**Comment by shunsuke44** [comment]
確かではありませんが、おそらくSqlite3のデータベース上のDatetimeはミリ秒位までしかサポートしていないのではないでしょうか?
どうしてもそのテストを書いて通したいのであれば、pythonの標準ライブラリの`sleep`などを使ってデータベースに保存する時間をずらすことも考えられます。そうでなければ存在のみを確認するテストにしてもいいでしょう。

**Comment by shizuka12** [comment]
`sleep`を使ったことで正しい順番で並ぶようになりました。
ありがとうございました。
