### ISSUE TITLE
自分自身をフォローできないことのテストの書き方

### ISSUE THREAD

**Issue by shizuka12** [shizuka12/final-tasks#7]
https://github.com/shizuka12/final-tasks/blob/16f7df64d691a088e5803a620cb05eb1508477c1/mysite/accounts/tests.py#L128-L135
自分自身をフォローできないことをテストしようとしたのですが、この133行目のコードでは、自分自身をフォローすることができてしまい、テストが上手くいきませんでした。
どのようなコードを書けば自分自身をフォローできないことをテストできるでしょうか？

**Comment by shunsuke44** [comment]
そもそもデータベースレベルでのバリデーションは設定されていないので、このテストコードでは自分自身をフォローできてしまいます。
ビューの動作をエミュレートするには`self.client.post`を使用します。

**Comment by shizuka12** [comment]
かなり初歩的なところでつまずいていましたね…。
`self.client.post`を使ったところ上手くできました。ありがとうございました。
